//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.Hrbl.Ordering.Adapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filuet.Hrbl.Ordering.Adapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Distributor&quot;:{&quot;DistributorType&quot;:&quot;DS&quot;,&quot;Discount&quot;:{&quot;DistributorDiscount&quot;:35,&quot;HerbalifeMinDiscount&quot;:0,&quot;HerbalifeMaxDiscount&quot;:50}}}.
        /// </summary>
        internal static string MockDistributorDiscount {
            get {
                return ResourceManager.GetString("MockDistributorDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;LimitAmount&quot;:0.0,&quot;CashAmountPaid&quot;:0.0,&quot;Responses&quot;:{&quot;Response&quot;:[{&quot;ResponseCode&quot;:&quot;0&quot;,&quot;ResponseMessage&quot;:&quot;SUCCESS: Req - 2021/02/19/90000031233 .&quot;}]}}.
        /// </summary>
        internal static string MockDSCashLimit {
            get {
                return ResourceManager.GetString("MockDSCashLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;DSFOPLimits&quot;:{
        ///      &quot;DSFOPLimit&quot;:{
        ///         &quot;EarnedFOP&quot;:{
        ///            &quot;@nil&quot;:&quot;true&quot;
        ///         },
        ///         &quot;AvailableFOPLimit&quot;:1080.79,
        ///         &quot;ThresholdFOPimit&quot;:3999.99,
        ///         &quot;FOPFirstOrderDate&quot;:&quot;2019-01-16T11:00:00+03:00&quot;,
        ///         &quot;FOPThresholdPeriod&quot;:29
        ///      }
        ///   },
        ///   &quot;DSOTLimits&quot;:null,
        ///   &quot;DSPurchasingLimits&quot;:{
        ///      &quot;DSPurchasingLimit&quot;:[
        ///         {
        ///            &quot;PPVOrderMonth&quot;:&quot;2021/02&quot;,
        ///            &quot;EarnedPC&quot;:-1,
        ///            &quot;AvailablePCLimit&quot;:-1,
        ///            &quot;Threshold [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MockDSFOPPurchasingLimit {
            get {
                return ResourceManager.GetString("MockDSFOPPurchasingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;DistributorId&quot;: &quot;MY660642&quot;,
        ///    &quot;TinDetails&quot;: {
        ///        &quot;DistributorTin&quot;: [
        ///            {
        ///                &quot;TinCode&quot;: &quot;MYID&quot;,
        ///                &quot;TinNumber&quot;: null,
        ///                &quot;TinCountry&quot;: &quot;MY&quot;,
        ///                &quot;EffectiveDate&quot;: &quot;2020-07-01T07:23:12.000-07:00&quot;,
        ///                &quot;ExpirationDate&quot;: &quot;2070-06-30T00:00:00.000-07:00&quot;,
        ///                &quot;ActiveFlag&quot;: &quot;Y&quot;
        ///            }
        ///        ]
        ///    },
        ///    &quot;Errors&quot;: {
        ///        &quot;Error&quot;: [
        ///            {
        ///                &quot;ErrorCode&quot;: &quot;0&quot;,
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MockMemberTins {
            get {
                return ResourceManager.GetString("MockMemberTins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;OrderPriceHeader&quot;:{&quot;DiscountPercent&quot;:50,&quot;VolumePoints&quot;:12.5,&quot;TotalFreightCharges&quot;:0.64,&quot;TotalPHCharges&quot;:0.0,&quot;TotalLogisticCharges&quot;:0.0,&quot;TotalOtherCharges&quot;:0.0,&quot;TotalTaxAmount&quot;:1.62,&quot;TotalRetailAmount&quot;:13.05,&quot;TotalOrderAmount&quot;:7.74,&quot;TotalDiscountAmount&quot;:5.95,&quot;TotalDue&quot;:9.36,&quot;TotalProductRetail&quot;:7.1,&quot;TotalLiteratureRetail&quot;:0.0,&quot;ExternalOrderNumber&quot;:&quot;LRK1350572&quot;,&quot;DistributorId&quot;:&quot;U515170226&quot;,&quot;Warehouse&quot;:&quot;LR&quot;,&quot;ProcessingLocation&quot;:&quot;LR&quot;,&quot;FreightCode&quot;:&quot;PU1&quot;,&quot;CountryCode&quot;:&quot;LV&quot;,&quot;OrderMonth&quot;:&quot;2102&quot;,&quot;OrderCategory&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MockPricingResponse {
            get {
                return ResourceManager.GetString("MockPricingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;DistributorName&quot;:&quot;VALENTINA VASILEVA&quot;,
        ///   &quot;DistributorId&quot;:&quot;7918180560&quot;,
        ///   &quot;DistributorShip&quot;:{
        ///      &quot;Type&quot;:&quot;SELF&quot;,
        ///      &quot;PartyId&quot;:&quot;44461955&quot;,
        ///      &quot;PartyNumber&quot;:null,
        ///      &quot;PartyName&quot;:&quot;VALENTINA VASILEVA&quot;,
        ///      &quot;FirstName&quot;:&quot;VALENTINA&quot;,
        ///      &quot;LastName&quot;:&quot;VASILEVA&quot;,
        ///      &quot;MiddleName&quot;:&quot;NIKOLAEVNA&quot;,
        ///      &quot;FirstNameLocal&quot;:&quot;ВАЛЕНТИНА&quot;,
        ///      &quot;LastNameLocal&quot;:&quot;ВАСИЛЬЕВА&quot;,
        ///      &quot;MiddleNameLocal&quot;:&quot;НИКОЛАЕВНА&quot;,
        ///      &quot;SpouseFirstName&quot;:null,
        ///      &quot;SpouseLastName&quot;:null,
        ///      &quot;SpouseMiddle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MockProfileResponse {
            get {
                return ResourceManager.GetString("MockProfileResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;OrderMonth&quot;:&quot;yyyy/MM&quot;,&quot;DistPPV&quot;:0.0,&quot;DistDLV&quot;:0.0,&quot;DistPV&quot;:0.0,&quot;DistGV&quot;:0.0,&quot;DistTV&quot;:0.0,&quot;DistRO&quot;:0.0,&quot;DistMPV&quot;:0.0,&quot;DistMTV&quot;:0.0,&quot;Dist3PPV&quot;:98.5,&quot;Dist12PPV&quot;:282.1,&quot;DistUV&quot;:0.0,&quot;DistEV&quot;:0.0,&quot;UvEvLastUpdateDate&quot;:null,&quot;Dist3DLV&quot;:0.0,&quot;Dist12DLV&quot;:0.0,&quot;Dist6PPV&quot;:209.25,&quot;Dist6DLV&quot;:0.0,&quot;Dist2PPV&quot;:0.0,&quot;CDLV&quot;:0.0,&quot;PM_12DLV&quot;:0.0}].
        /// </summary>
        internal static string MockVP {
            get {
                return ResourceManager.GetString("MockVP", resourceCulture);
            }
        }
    }
}
