// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for GetDistributorVolumePoints.
    /// </summary>
    public static partial class GetDistributorVolumePointsExtensions
    {
            /// <summary>
            /// GetDistributorVolumePoints_POST
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static void POST(this IGetDistributorVolumePoints operations, object body)
            {
                operations.POSTAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// GetDistributorVolumePoints_POST
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task POSTAsync(this IGetDistributorVolumePoints operations, object body, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.POSTWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
