// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IHLOnlineOrderingRS : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }
void SetTimeout(System.TimeSpan timeout);
void ResetTimeout();

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IApiValidate.
        /// </summary>
        IApiValidate ApiValidate { get; }

        /// <summary>
        /// Gets the IGetPriceDetails.
        /// </summary>
        IGetPriceDetails GetPriceDetails { get; }

        /// <summary>
        /// Gets the IHPSPaymentGateway.
        /// </summary>
        IHPSPaymentGateway HPSPaymentGateway { get; }

        /// <summary>
        /// Gets the IGetDistributorProfile.
        /// </summary>
        IGetDistributorProfile GetDistributorProfile { get; }

        /// <summary>
        /// Gets the IGetSkuAvailability.
        /// </summary>
        IGetSkuAvailability GetSkuAvailability { get; }

        /// <summary>
        /// Gets the ISubmitOrder.
        /// </summary>
        ISubmitOrder SubmitOrder { get; }

        /// <summary>
        /// Gets the IGetDistributorDiscount.
        /// </summary>
        IGetDistributorDiscount GetDistributorDiscount { get; }

        /// <summary>
        /// Gets the IDSFOPPurchasingLimits.
        /// </summary>
        IDSFOPPurchasingLimits DSFOPPurchasingLimits { get; }

        /// <summary>
        /// Gets the IDsCashLimit.
        /// </summary>
        IDsCashLimit DsCashLimit { get; }

        /// <summary>
        /// Gets the IGetOrderDualMonthStatus.
        /// </summary>
        IGetOrderDualMonthStatus GetOrderDualMonthStatus { get; }

        /// <summary>
        /// Gets the IUpdateDsAddressContacts.
        /// </summary>
        IUpdateDsAddressContacts UpdateDsAddressContacts { get; }

        /// <summary>
        /// Gets the IGetShippingWhseAndFreightCodes.
        /// </summary>
        IGetShippingWhseAndFreightCodes GetShippingWhseAndFreightCodes { get; }

        /// <summary>
        /// Gets the IGetDSPostamatDetails.
        /// </summary>
        IGetDSPostamatDetails GetDSPostamatDetails { get; }

        /// <summary>
        /// Gets the IGetProductInventory.
        /// </summary>
        IGetProductInventory GetProductInventory { get; }

        /// <summary>
        /// Gets the IGetProductCatalog.
        /// </summary>
        IGetProductCatalog GetProductCatalog { get; }

        /// <summary>
        /// Gets the IGetDistributorVolumePoints.
        /// </summary>
        IGetDistributorVolumePoints GetDistributorVolumePoints { get; }

    }
}
