// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Body4
    {
        /// <summary>
        /// Initializes a new instance of the Body4 class.
        /// </summary>
        public Body4()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body4 class.
        /// </summary>
        public Body4(IList<OrderHLOnlineOrderingts3SubmitOrderOrderLine> orderLine = default(IList<OrderHLOnlineOrderingts3SubmitOrderOrderLine>), OrderHLOnlineOrderingts3SubmitOrderOrderNotes orderNotes = default(OrderHLOnlineOrderingts3SubmitOrderOrderNotes), OrderHLOnlineOrderingts3SubmitOrderOrderHeaders orderHeaders = default(OrderHLOnlineOrderingts3SubmitOrderOrderHeaders), OrderHLOnlineOrderingts3SubmitOrderOrderAddress orderAddress = default(OrderHLOnlineOrderingts3SubmitOrderOrderAddress), OrderHLOnlineOrderingts3SubmitOrderOrderPayment orderPayment = default(OrderHLOnlineOrderingts3SubmitOrderOrderPayment), OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine orderPromotionLine = default(OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine), string serviceConsumer = default(string))
        {
            OrderLine = orderLine;
            OrderNotes = orderNotes;
            OrderHeaders = orderHeaders;
            OrderAddress = orderAddress;
            OrderPayment = orderPayment;
            OrderPromotionLine = orderPromotionLine;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderLine")]
        public IList<OrderHLOnlineOrderingts3SubmitOrderOrderLine> OrderLine { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderNotes")]
        public OrderHLOnlineOrderingts3SubmitOrderOrderNotes OrderNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderHeaders")]
        public OrderHLOnlineOrderingts3SubmitOrderOrderHeaders OrderHeaders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderAddress")]
        public OrderHLOnlineOrderingts3SubmitOrderOrderAddress OrderAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderPayment")]
        public OrderHLOnlineOrderingts3SubmitOrderOrderPayment OrderPayment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderPromotionLine")]
        public OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine OrderPromotionLine { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
