// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Body12
    {
        /// <summary>
        /// Initializes a new instance of the Body12 class.
        /// </summary>
        public Body12()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body12 class.
        /// </summary>
        public Body12(OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceHeader orderPriceHeader = default(OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceHeader), IList<OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines> orderPriceLines = default(IList<OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines>), string serviceConsumer = default(string))
        {
            OrderPriceHeader = orderPriceHeader;
            OrderPriceLines = orderPriceLines;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderPriceHeader")]
        public OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceHeader OrderPriceHeader { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderPriceLines")]
        public IList<OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines> OrderPriceLines { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
