// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body8
    {
        /// <summary>
        /// Initializes a new instance of the Body8 class.
        /// </summary>
        public Body8()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body8 class.
        /// </summary>
        public Body8(string distributorId = default(string), string shipToCountry = default(string), string orderPurpose = default(string), string orderMonth = default(string), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode volumePoints = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode iDType = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string serviceConsumer = default(string))
        {
            DistributorId = distributorId;
            ShipToCountry = shipToCountry;
            OrderPurpose = orderPurpose;
            OrderMonth = orderMonth;
            VolumePoints = volumePoints;
            IDType = iDType;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistributorId")]
        public string DistributorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipToCountry")]
        public string ShipToCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderPurpose")]
        public string OrderPurpose { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderMonth")]
        public string OrderMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VolumePoints")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode VolumePoints { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IDType")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode IDType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
