// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body14
    {
        /// <summary>
        /// Initializes a new instance of the Body14 class.
        /// </summary>
        public Body14()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body14 class.
        /// </summary>
        public Body14(string shipToCountry = default(string))
        {
            ShipToCountry = shipToCountry;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipToCountry")]
        public string ShipToCountry { get; set; }

    }
}
