// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body9
    {
        /// <summary>
        /// Initializes a new instance of the Body9 class.
        /// </summary>
        public Body9()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body9 class.
        /// </summary>
        public Body9(string distributorId = default(string), OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress address = default(OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress), OrderHLOnlineOrderingts3UpdateDsAddressContactsContact contact = default(OrderHLOnlineOrderingts3UpdateDsAddressContactsContact), string serviceConsumer = default(string))
        {
            DistributorId = distributorId;
            Address = address;
            Contact = contact;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistributorId")]
        public string DistributorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contact")]
        public OrderHLOnlineOrderingts3UpdateDsAddressContactsContact Contact { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
