// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body3
    {
        /// <summary>
        /// Initializes a new instance of the Body3 class.
        /// </summary>
        public Body3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body3 class.
        /// </summary>
        public Body3(string postalCode = default(string), string expressDeliveryFlag = default(string), string serviceConsumer = default(string))
        {
            PostalCode = postalCode;
            ExpressDeliveryFlag = expressDeliveryFlag;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostalCode")]
        public string PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpressDeliveryFlag")]
        public string ExpressDeliveryFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
