// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body13
    {
        /// <summary>
        /// Initializes a new instance of the Body13 class.
        /// </summary>
        public Body13()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body13 class.
        /// </summary>
        public Body13(string distributorID = default(string), string countryCode = default(string), string serviceConsumer = default(string))
        {
            DistributorID = distributorID;
            CountryCode = countryCode;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistributorID")]
        public string DistributorID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CountryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
