// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body5
    {
        /// <summary>
        /// Initializes a new instance of the Body5 class.
        /// </summary>
        public Body5()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body5 class.
        /// </summary>
        public Body5(OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest paymentRequest = default(OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest), string serviceConsumer = default(string))
        {
            PaymentRequest = paymentRequest;
            ServiceConsumer = serviceConsumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PaymentRequest")]
        public OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest PaymentRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

    }
}
