// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body
    {
        /// <summary>
        /// Initializes a new instance of the Body class.
        /// </summary>
        public Body()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body class.
        /// </summary>
        public Body(string distributorId = default(string), string toMonth = default(string), string fromMonth = default(string), string serviceConsumer = default(string), string includeORgVolumes = default(string))
        {
            DistributorId = distributorId;
            ToMonth = toMonth;
            FromMonth = fromMonth;
            ServiceConsumer = serviceConsumer;
            IncludeORgVolumes = includeORgVolumes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistributorId")]
        public string DistributorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToMonth")]
        public string ToMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromMonth")]
        public string FromMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceConsumer")]
        public string ServiceConsumer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludeORgVolumes")]
        public string IncludeORgVolumes { get; set; }

    }
}
