// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Body1
    {
        /// <summary>
        /// Initializes a new instance of the Body1 class.
        /// </summary>
        public Body1()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Body1 class.
        /// </summary>
        public Body1(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode zipCode = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string country = default(string), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode region = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode city = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string postamatType = default(string))
        {
            ZipCode = zipCode;
            Country = country;
            Region = region;
            City = city;
            PostamatType = postamatType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipCode")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode ZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Region")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostamatType")]
        public string PostamatType { get; set; }

    }
}
