// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3SubmitOrderOrderHeadersHeaderTaxBreakup
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderHeadersHeaderTaxBreakup
        /// class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderHeadersHeaderTaxBreakup()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderHeadersHeaderTaxBreakup
        /// class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderHeadersHeaderTaxBreakup(object taxName = default(object), object taxValue = default(object), object taxRate = default(object), string nil = default(string))
        {
            TaxName = taxName;
            TaxValue = taxValue;
            TaxRate = taxRate;
            Nil = nil;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxName")]
        public object TaxName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxValue")]
        public object TaxValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxRate")]
        public object TaxRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@nil")]
        public string Nil { get; set; }

    }
}
