// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3SubmitOrderOrderPaymentCreditCard
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderPaymentCreditCard class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderPaymentCreditCard()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderPaymentCreditCard class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderPaymentCreditCard(string cardNumber = default(string), string cardValidationType = default(string), string trxApprovalNumber = default(string), string cardType = default(string), string cardHolderRelation = default(string), string cardExpiryDate = default(string), object cardTypeDescription = default(object), string cardHolderName = default(string))
        {
            CardNumber = cardNumber;
            CardValidationType = cardValidationType;
            TrxApprovalNumber = trxApprovalNumber;
            CardType = cardType;
            CardHolderRelation = cardHolderRelation;
            CardExpiryDate = cardExpiryDate;
            CardTypeDescription = cardTypeDescription;
            CardHolderName = cardHolderName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardNumber")]
        public string CardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardValidationType")]
        public string CardValidationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TrxApprovalNumber")]
        public string TrxApprovalNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardHolderRelation")]
        public string CardHolderRelation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardExpiryDate")]
        public string CardExpiryDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardTypeDescription")]
        public object CardTypeDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardHolderName")]
        public string CardHolderName { get; set; }

    }
}
