// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3SubmitOrderOrderAddress
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderAddress class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderAddress class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderAddress(object csPhoneNumber = default(object), object externalOrderNumber = default(object), object postalCode = default(object), object county = default(object), object iDType = default(object), string nil = default(string), object address4 = default(object), object badAddressFlag = default(object), object zipplusFour = default(object), object validCsAddressFlag = default(object), object customerName = default(object), object csEmailValidFlag = default(object), object countryCode = default(object), object addressUid = default(object), object csFirstName = default(object), object csPhoneAreaCode = default(object), object csLastName = default(object), object foreignAddressflag = default(object), object csEMail = default(object), object csPhoneValidFlag = default(object), object address2 = default(object), object address3 = default(object), object csEmailUid = default(object), object address1 = default(object), object city = default(object), object csPhoneUid = default(object), object state = default(object), object addressType = default(object))
        {
            CsPhoneNumber = csPhoneNumber;
            ExternalOrderNumber = externalOrderNumber;
            PostalCode = postalCode;
            County = county;
            IDType = iDType;
            Nil = nil;
            Address4 = address4;
            BadAddressFlag = badAddressFlag;
            ZipplusFour = zipplusFour;
            ValidCsAddressFlag = validCsAddressFlag;
            CustomerName = customerName;
            CsEmailValidFlag = csEmailValidFlag;
            CountryCode = countryCode;
            AddressUid = addressUid;
            CsFirstName = csFirstName;
            CsPhoneAreaCode = csPhoneAreaCode;
            CsLastName = csLastName;
            ForeignAddressflag = foreignAddressflag;
            CsEMail = csEMail;
            CsPhoneValidFlag = csPhoneValidFlag;
            Address2 = address2;
            Address3 = address3;
            CsEmailUid = csEmailUid;
            Address1 = address1;
            City = city;
            CsPhoneUid = csPhoneUid;
            State = state;
            AddressType = addressType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsPhoneNumber")]
        public object CsPhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalOrderNumber")]
        public object ExternalOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostalCode")]
        public object PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "County")]
        public object County { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IDType")]
        public object IDType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@nil")]
        public string Nil { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address4")]
        public object Address4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BadAddressFlag")]
        public object BadAddressFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipplusFour")]
        public object ZipplusFour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ValidCsAddressFlag")]
        public object ValidCsAddressFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerName")]
        public object CustomerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsEmailValidFlag")]
        public object CsEmailValidFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CountryCode")]
        public object CountryCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressUid")]
        public object AddressUid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsFirstName")]
        public object CsFirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsPhoneAreaCode")]
        public object CsPhoneAreaCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsLastName")]
        public object CsLastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ForeignAddressflag")]
        public object ForeignAddressflag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsEMail")]
        public object CsEMail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsPhoneValidFlag")]
        public object CsPhoneValidFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address2")]
        public object Address2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address3")]
        public object Address3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsEmailUid")]
        public object CsEmailUid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address1")]
        public object Address1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public object City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CsPhoneUid")]
        public object CsPhoneUid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public object State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressType")]
        public object AddressType { get; set; }

    }
}
