// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetPriceDetailsOrderPriceLines(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode currencyCode = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string priceDate = default(string), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode uOM = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string processingLocation = default(string), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode priceListHeaderId = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode externalOrderNumber = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode orderedQtyUOM = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string sellingSKU = default(string), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode inventoryItemId = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode), string productType = default(string), string orderedQty = default(string), OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode lineNumber = default(OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode))
        {
            CurrencyCode = currencyCode;
            PriceDate = priceDate;
            UOM = uOM;
            ProcessingLocation = processingLocation;
            PriceListHeaderId = priceListHeaderId;
            ExternalOrderNumber = externalOrderNumber;
            OrderedQtyUOM = orderedQtyUOM;
            SellingSKU = sellingSKU;
            InventoryItemId = inventoryItemId;
            ProductType = productType;
            OrderedQty = orderedQty;
            LineNumber = lineNumber;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CurrencyCode")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode CurrencyCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PriceDate")]
        public string PriceDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UOM")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode UOM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProcessingLocation")]
        public string ProcessingLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PriceListHeaderId")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode PriceListHeaderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalOrderNumber")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode ExternalOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderedQtyUOM")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode OrderedQtyUOM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SellingSKU")]
        public string SellingSKU { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InventoryItemId")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode InventoryItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductType")]
        public string ProductType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderedQty")]
        public string OrderedQty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LineNumber")]
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode LineNumber { get; set; }

    }
}
