// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderPromotionLine(object dateAttribute5 = default(object), object dateAttribute4 = default(object), object redemptionType = default(object), object dateAttribute3 = default(object), object dateAttribute2 = default(object), object chrAttribute8 = default(object), object dateAttribute1 = default(object), object chrAttribute7 = default(object), object chrAttribute9 = default(object), object chrAttribute4 = default(object), object chrAttribute3 = default(object), object chrAttribute6 = default(object), object chrAttribute5 = default(object), object promotionItem = default(object), object dateAttribute9 = default(object), object dateAttribute8 = default(object), object chrAttribute2 = default(object), object dateAttribute7 = default(object), string nil = default(string), object chrAttribute1 = default(object), object dateAttribute6 = default(object), object numAttribute6 = default(object), object numAttribute7 = default(object), object ruleName = default(object), object numAttribute8 = default(object), object numAttribute9 = default(object), object numAttribute2 = default(object), object numAttribute3 = default(object), object numAttribute4 = default(object), object numAttribute5 = default(object), object ruleID = default(object), object promotionCode = default(object), object numAttribute1 = default(object), object quantity = default(object), object isAddedToOrder = default(object), object dateAttribute10 = default(object), object sKU = default(object), object numAttribute10 = default(object), object chrAttribute10 = default(object))
        {
            DateAttribute5 = dateAttribute5;
            DateAttribute4 = dateAttribute4;
            RedemptionType = redemptionType;
            DateAttribute3 = dateAttribute3;
            DateAttribute2 = dateAttribute2;
            ChrAttribute8 = chrAttribute8;
            DateAttribute1 = dateAttribute1;
            ChrAttribute7 = chrAttribute7;
            ChrAttribute9 = chrAttribute9;
            ChrAttribute4 = chrAttribute4;
            ChrAttribute3 = chrAttribute3;
            ChrAttribute6 = chrAttribute6;
            ChrAttribute5 = chrAttribute5;
            PromotionItem = promotionItem;
            DateAttribute9 = dateAttribute9;
            DateAttribute8 = dateAttribute8;
            ChrAttribute2 = chrAttribute2;
            DateAttribute7 = dateAttribute7;
            Nil = nil;
            ChrAttribute1 = chrAttribute1;
            DateAttribute6 = dateAttribute6;
            NumAttribute6 = numAttribute6;
            NumAttribute7 = numAttribute7;
            RuleName = ruleName;
            NumAttribute8 = numAttribute8;
            NumAttribute9 = numAttribute9;
            NumAttribute2 = numAttribute2;
            NumAttribute3 = numAttribute3;
            NumAttribute4 = numAttribute4;
            NumAttribute5 = numAttribute5;
            RuleID = ruleID;
            PromotionCode = promotionCode;
            NumAttribute1 = numAttribute1;
            Quantity = quantity;
            IsAddedToOrder = isAddedToOrder;
            DateAttribute10 = dateAttribute10;
            SKU = sKU;
            NumAttribute10 = numAttribute10;
            ChrAttribute10 = chrAttribute10;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute5")]
        public object DateAttribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute4")]
        public object DateAttribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RedemptionType")]
        public object RedemptionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute3")]
        public object DateAttribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute2")]
        public object DateAttribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute8")]
        public object ChrAttribute8 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute1")]
        public object DateAttribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute7")]
        public object ChrAttribute7 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute9")]
        public object ChrAttribute9 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute4")]
        public object ChrAttribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute3")]
        public object ChrAttribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute6")]
        public object ChrAttribute6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute5")]
        public object ChrAttribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PromotionItem")]
        public object PromotionItem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute9")]
        public object DateAttribute9 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute8")]
        public object DateAttribute8 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute2")]
        public object ChrAttribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute7")]
        public object DateAttribute7 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@nil")]
        public string Nil { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute1")]
        public object ChrAttribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute6")]
        public object DateAttribute6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute6")]
        public object NumAttribute6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute7")]
        public object NumAttribute7 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RuleName")]
        public object RuleName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute8")]
        public object NumAttribute8 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute9")]
        public object NumAttribute9 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute2")]
        public object NumAttribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute3")]
        public object NumAttribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute4")]
        public object NumAttribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute5")]
        public object NumAttribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RuleID")]
        public object RuleID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PromotionCode")]
        public object PromotionCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute1")]
        public object NumAttribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public object Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAddedToOrder")]
        public object IsAddedToOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute10")]
        public object DateAttribute10 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SKU")]
        public object SKU { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute10")]
        public object NumAttribute10 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute10")]
        public object ChrAttribute10 { get; set; }

    }
}
