// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3GetSkuAvailabilitySkuInquiryDetails
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetSkuAvailabilitySkuInquiryDetails class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetSkuAvailabilitySkuInquiryDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetSkuAvailabilitySkuInquiryDetails class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetSkuAvailabilitySkuInquiryDetails(OrderHLOnlineOrderingts3GetSkuAvailabilitySku sku = default(OrderHLOnlineOrderingts3GetSkuAvailabilitySku))
        {
            Sku = sku;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sku")]
        public OrderHLOnlineOrderingts3GetSkuAvailabilitySku Sku { get; set; }

    }
}
