// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetDSPostamatDetailsZipCode(string nil = default(string))
        {
            Nil = nil;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@nil")]
        public string Nil { get; set; }

    }
}
