// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3SubmitOrderLinesTaxBreakup
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderLinesTaxBreakup class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderLinesTaxBreakup()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderLinesTaxBreakup class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderLinesTaxBreakup(object taxName = default(object), object taxValue = default(object), object taxRate = default(object))
        {
            TaxName = taxName;
            TaxValue = taxValue;
            TaxRate = taxRate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxName")]
        public object TaxName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxValue")]
        public object TaxValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxRate")]
        public object TaxRate { get; set; }

    }
}
