// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress class.
        /// </summary>
        public OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress class.
        /// </summary>
        public OrderHLOnlineOrderingts3UpdateDsAddressContactsAddress(object building = default(object), object careOfName = default(object), object siteId = default(object), object attribute9 = default(object), object attribute8 = default(object), object attribute7 = default(object), object attribute6 = default(object), object isActive = default(object), object attribute5 = default(object), object attribute4 = default(object), object attribute3 = default(object), object attribute2 = default(object), object attribute1 = default(object), object county = default(object), object reason = default(object), object zipPlusFour = default(object), object geoCode = default(object), object fedexLocation = default(object), string zipCode = default(string), object attribute10 = default(object), string city = default(string), object province = default(object), object addressLine3 = default(object), object addressLine2 = default(object), string addressLine1 = default(string), object state = default(object), object addressLine4 = default(object), object isPrimary = default(object), object suburb = default(object), string country = default(string), string addressType = default(string), object lastUpdateDate = default(object))
        {
            Building = building;
            CareOfName = careOfName;
            SiteId = siteId;
            Attribute9 = attribute9;
            Attribute8 = attribute8;
            Attribute7 = attribute7;
            Attribute6 = attribute6;
            IsActive = isActive;
            Attribute5 = attribute5;
            Attribute4 = attribute4;
            Attribute3 = attribute3;
            Attribute2 = attribute2;
            Attribute1 = attribute1;
            County = county;
            Reason = reason;
            ZipPlusFour = zipPlusFour;
            GeoCode = geoCode;
            FedexLocation = fedexLocation;
            ZipCode = zipCode;
            Attribute10 = attribute10;
            City = city;
            Province = province;
            AddressLine3 = addressLine3;
            AddressLine2 = addressLine2;
            AddressLine1 = addressLine1;
            State = state;
            AddressLine4 = addressLine4;
            IsPrimary = isPrimary;
            Suburb = suburb;
            Country = country;
            AddressType = addressType;
            LastUpdateDate = lastUpdateDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Building")]
        public object Building { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CareOfName")]
        public object CareOfName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SiteId")]
        public object SiteId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute9")]
        public object Attribute9 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute8")]
        public object Attribute8 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute7")]
        public object Attribute7 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute6")]
        public object Attribute6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsActive")]
        public object IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute5")]
        public object Attribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute4")]
        public object Attribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute3")]
        public object Attribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute2")]
        public object Attribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute1")]
        public object Attribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "County")]
        public object County { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Reason")]
        public object Reason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipPlusFour")]
        public object ZipPlusFour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "geo_code")]
        public object GeoCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FedexLocation")]
        public object FedexLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipCode")]
        public string ZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute10")]
        public object Attribute10 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Province")]
        public object Province { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressLine3")]
        public object AddressLine3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressLine2")]
        public object AddressLine2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public object State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressLine4")]
        public object AddressLine4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsPrimary")]
        public object IsPrimary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suburb")]
        public object Suburb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressType")]
        public string AddressType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastUpdateDate")]
        public object LastUpdateDate { get; set; }

    }
}
