// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3UpdateDsAddressContactsContact
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3UpdateDsAddressContactsContact class.
        /// </summary>
        public OrderHLOnlineOrderingts3UpdateDsAddressContactsContact()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3UpdateDsAddressContactsContact class.
        /// </summary>
        public OrderHLOnlineOrderingts3UpdateDsAddressContactsContact(string type = default(string), string subType = default(string), string oldValue = default(string), string isActive = default(string), object attribute5 = default(object), object attribute4 = default(object), string value = default(string), string isPrimary = default(string), object attribute3 = default(object), object attribute2 = default(object), object attribute1 = default(object), object lastUpdateDate = default(object))
        {
            Type = type;
            SubType = subType;
            OldValue = oldValue;
            IsActive = isActive;
            Attribute5 = attribute5;
            Attribute4 = attribute4;
            Value = value;
            IsPrimary = isPrimary;
            Attribute3 = attribute3;
            Attribute2 = attribute2;
            Attribute1 = attribute1;
            LastUpdateDate = lastUpdateDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubType")]
        public string SubType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OldValue")]
        public string OldValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsActive")]
        public string IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute5")]
        public object Attribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute4")]
        public object Attribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsPrimary")]
        public string IsPrimary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute3")]
        public object Attribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute2")]
        public object Attribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute1")]
        public object Attribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastUpdateDate")]
        public object LastUpdateDate { get; set; }

    }
}
