// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3GetSkuAvailabilitySku
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetSkuAvailabilitySku class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetSkuAvailabilitySku()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3GetSkuAvailabilitySku class.
        /// </summary>
        public OrderHLOnlineOrderingts3GetSkuAvailabilitySku(string skuName = default(string), string quantity = default(string), string warehouseCode = default(string))
        {
            SkuName = skuName;
            Quantity = quantity;
            WarehouseCode = warehouseCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SkuName")]
        public string SkuName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WarehouseCode")]
        public string WarehouseCode { get; set; }

    }
}
