// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3SubmitOrderOrderNotes
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderNotes class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderNotes()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3SubmitOrderOrderNotes class.
        /// </summary>
        public OrderHLOnlineOrderingts3SubmitOrderOrderNotes(object numAttribute2 = default(object), object dateAttribute5 = default(object), object numAttribute3 = default(object), object dateAttribute4 = default(object), object numAttribute4 = default(object), object dateAttribute3 = default(object), object numAttribute5 = default(object), object dateAttribute2 = default(object), object chrAttribute8 = default(object), object dateAttribute1 = default(object), object chrAttribute7 = default(object), object externalOrderNumber = default(object), object chrAttribute9 = default(object), object numAttribute1 = default(object), object chrAttribute4 = default(object), object chrAttribute3 = default(object), object chrAttribute6 = default(object), object chrAttribute5 = default(object), object chrAttribute2 = default(object), object noteCode = default(object), object chrAttribute1 = default(object), object noteMessage = default(object), object chrAttribute10 = default(object))
        {
            NumAttribute2 = numAttribute2;
            DateAttribute5 = dateAttribute5;
            NumAttribute3 = numAttribute3;
            DateAttribute4 = dateAttribute4;
            NumAttribute4 = numAttribute4;
            DateAttribute3 = dateAttribute3;
            NumAttribute5 = numAttribute5;
            DateAttribute2 = dateAttribute2;
            ChrAttribute8 = chrAttribute8;
            DateAttribute1 = dateAttribute1;
            ChrAttribute7 = chrAttribute7;
            ExternalOrderNumber = externalOrderNumber;
            ChrAttribute9 = chrAttribute9;
            NumAttribute1 = numAttribute1;
            ChrAttribute4 = chrAttribute4;
            ChrAttribute3 = chrAttribute3;
            ChrAttribute6 = chrAttribute6;
            ChrAttribute5 = chrAttribute5;
            ChrAttribute2 = chrAttribute2;
            NoteCode = noteCode;
            ChrAttribute1 = chrAttribute1;
            NoteMessage = noteMessage;
            ChrAttribute10 = chrAttribute10;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute2")]
        public object NumAttribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute5")]
        public object DateAttribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute3")]
        public object NumAttribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute4")]
        public object DateAttribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute4")]
        public object NumAttribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute3")]
        public object DateAttribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute5")]
        public object NumAttribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute2")]
        public object DateAttribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute8")]
        public object ChrAttribute8 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAttribute1")]
        public object DateAttribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute7")]
        public object ChrAttribute7 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalOrderNumber")]
        public object ExternalOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute9")]
        public object ChrAttribute9 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumAttribute1")]
        public object NumAttribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute4")]
        public object ChrAttribute4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute3")]
        public object ChrAttribute3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute6")]
        public object ChrAttribute6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute5")]
        public object ChrAttribute5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute2")]
        public object ChrAttribute2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NoteCode")]
        public object NoteCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute1")]
        public object ChrAttribute1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NoteMessage")]
        public object NoteMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChrAttribute10")]
        public object ChrAttribute10 { get; set; }

    }
}
