// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Filuet.Fusion.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest class.
        /// </summary>
        public OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest class.
        /// </summary>
        public OrderHLOnlineOrderingts3HPSPaymentGatewayPaymentRequest(string operatorProperty = default(string), string distributorId = default(string), string expiryDate = default(string), string processingLocation = default(string), string clientRefNum = default(string), string amount = default(string), string postalCode = default(string), string orderNumber = default(string), object transactionclass = default(object), string address1 = default(string), string city = default(string), string cardHolderName = default(string), string cVV2 = default(string), object payeeID = default(object), string applicationSource = default(string), string orderType = default(string), string payCode = default(string), string currency = default(string), string country = default(string), string paymentType = default(string), string creditCardNum = default(string))
        {
            OperatorProperty = operatorProperty;
            DistributorId = distributorId;
            ExpiryDate = expiryDate;
            ProcessingLocation = processingLocation;
            ClientRefNum = clientRefNum;
            Amount = amount;
            PostalCode = postalCode;
            OrderNumber = orderNumber;
            Transactionclass = transactionclass;
            Address1 = address1;
            City = city;
            CardHolderName = cardHolderName;
            CVV2 = cVV2;
            PayeeID = payeeID;
            ApplicationSource = applicationSource;
            OrderType = orderType;
            PayCode = payCode;
            Currency = currency;
            Country = country;
            PaymentType = paymentType;
            CreditCardNum = creditCardNum;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Operator")]
        public string OperatorProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistributorId")]
        public string DistributorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpiryDate")]
        public string ExpiryDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProcessingLocation")]
        public string ProcessingLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientRefNum")]
        public string ClientRefNum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public string Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostalCode")]
        public string PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transactionclass")]
        public object Transactionclass { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address1")]
        public string Address1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardHolderName")]
        public string CardHolderName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CVV2")]
        public string CVV2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PayeeID")]
        public object PayeeID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicationSource")]
        public string ApplicationSource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderType")]
        public string OrderType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PayCode")]
        public string PayCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PaymentType")]
        public string PaymentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreditCardNum")]
        public string CreditCardNum { get; set; }

    }
}
